export interface BusinessPreset {
  id: string;
  name: string;
  description: string;
  icon: string;
  gradient: string;
  color: string;
  categories: string[];
  systemPrompt: string;
  suggestedMessages: string[];
  welcomeMessage: string;
  quickActions: string[];
  analyticsTags: string[];
}

export const BUSINESS_PRESETS: BusinessPreset[] = [
  {
    id: 'portfolio',
    name: 'Portfolio',
    description: 'Showcase work, accept inquiries, book consultations',
    icon: '🎨',
    gradient: 'from-rose-500 to-pink-500',
    color: '#e11d48',
    categories: ['Designer', 'Developer', 'Artist', 'Photographer', 'Freelancer'],
    systemPrompt: 'You are a portfolio assistant. Help visitors learn about the portfolio owner, their work, services offered, and how to book their services. Be creative and showcase enthusiasm for their craft.',
    suggestedMessages: ['View my work', 'Services & pricing', 'Book a call', 'Get a quote'],
    welcomeMessage: 'Welcome! 👋 I can help you explore the portfolio, learn about services, and book a consultation.',
    quickActions: ['Book Consultation', 'View Gallery', 'Download Resume', 'Contact Me'],
    analyticsTags: ['portfolio', 'freelance', 'creative', 'booking'],
  },
  {
    id: 'agency',
    name: 'Agency',
    description: 'Lead generation, service inquiries, project proposals',
    icon: '🏢',
    gradient: 'from-blue-500 to-cyan-500',
    color: '#0ea5e9',
    categories: ['Marketing', 'Development', 'Design', 'Consulting', 'Media'],
    systemPrompt: 'You are a business development assistant for a digital agency. Help potential clients understand services, view case studies, request proposals, and start projects. Be professional and persuasive.',
    suggestedMessages: ['View our work', 'Services overview', 'Request proposal', 'Case studies'],
    welcomeMessage: 'Welcome to our agency! 🚀 Tell us about your project and we\'ll help bring it to life.',
    quickActions: ['Request Proposal', 'View Case Studies', 'Schedule Call', 'Our Services'],
    analyticsTags: ['agency', 'b2b', 'leads', 'proposals'],
  },
  {
    id: 'ecommerce',
    name: 'E-commerce',
    description: 'Product discovery, order support, cart recovery',
    icon: '🛍️',
    gradient: 'from-purple-500 to-pink-500',
    color: '#a855f7',
    categories: ['Retail', 'Fashion', 'Electronics', 'Marketplace', 'D2C'],
    systemPrompt: 'You are an e-commerce shopping assistant. Help customers find products, compare items, track orders, process returns, and answer questions about shipping and availability. Be friendly and focus on conversion.',
    suggestedMessages: ['Track my order', 'Find products', 'Return policy', 'Best sellers'],
    welcomeMessage: 'Hi there! 👋 Looking for something specific? I can help you find the perfect product!',
    quickActions: ['Track Order', 'Browse Categories', 'Deals & Offers', 'Help Center'],
    analyticsTags: ['ecommerce', 'retail', 'sales', 'support'],
  },
  {
    id: 'clinic',
    name: 'Clinic',
    description: 'Appointment booking, patient intake, service info',
    icon: '🏥',
    gradient: 'from-green-500 to-emerald-500',
    color: '#10b981',
    categories: ['Medical', 'Dental', 'Veterinary', 'Wellness', 'Spa'],
    systemPrompt: 'You are a healthcare clinic assistant. Help patients schedule appointments, provide pre-visit information, answer billing questions, and share health resources. Always include medical disclaimers.',
    suggestedMessages: ['Book appointment', 'Our services', 'Insurance info', 'Prepare for visit'],
    welcomeMessage: 'Welcome to our clinic! 🏥 How can I help you with your healthcare needs?',
    quickActions: ['Book Appointment', 'Find a Doctor', 'Insurance Info', 'Patient Portal'],
    analyticsTags: ['healthcare', 'appointments', 'patient', 'clinic'],
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Reservations, menu info, catering inquiries',
    icon: '🍽️',
    gradient: 'from-amber-500 to-orange-500',
    color: '#f59e0b',
    categories: ['Fine Dining', 'Cafe', 'Bar', 'Fast Casual', 'Catering'],
    systemPrompt: 'You are a restaurant concierge. Help guests with reservations, menu questions, dietary restrictions, event bookings, and catering inquiries. Be warm and create excitement about the dining experience.',
    suggestedMessages: ['Make a reservation', 'View menu', 'Private events', 'Hours & location'],
    welcomeMessage: 'Welcome! 🍽️ Ready to book a table or explore our menu? I\'m here to help!',
    quickActions: ['Reserve a Table', 'View Menu', 'Order Online', 'Private Events'],
    analyticsTags: ['restaurant', 'hospitality', 'reservations', 'dining'],
  },
  {
    id: 'lawyer',
    name: 'Legal',
    description: 'Case intake, consultation booking, legal info',
    icon: '⚖️',
    gradient: 'from-slate-500 to-gray-500',
    color: '#64748b',
    categories: ['Law Firm', 'Attorney', 'Legal Services', 'Notary'],
    systemPrompt: 'You are a legal practice assistant. Help potential clients understand practice areas, book consultations, prepare for meetings, and answer general questions. Always include disclaimers and avoid giving specific legal advice.',
    suggestedMessages: ['Practice areas', 'Book consultation', 'Attorney profiles', 'Client resources'],
    welcomeMessage: 'Welcome to our practice. ⚖️ How can we assist you with your legal needs?',
    quickActions: ['Book Consultation', 'Practice Areas', 'Meet Our Team', 'Client Resources'],
    analyticsTags: ['legal', 'attorney', 'consultation', 'professional'],
  },
  {
    id: 'hr',
    name: 'HR & Recruitment',
    description: 'Job applications, candidate screening, employee support',
    icon: '👥',
    gradient: 'from-violet-500 to-indigo-500',
    color: '#8b5cf6',
    categories: ['Recruitment', 'HR Consulting', 'Staffing', 'Talent'],
    systemPrompt: 'You are an HR and recruitment assistant. Help candidates with job applications, screening questions, company culture info, and interview scheduling. Be professional and welcoming to potential talent.',
    suggestedMessages: ['Open positions', 'Apply now', 'Company culture', 'Application status'],
    welcomeMessage: 'Welcome to our careers portal! 👥 Explore opportunities and join our team!',
    quickActions: ['View Openings', 'Submit Application', 'Culture & Benefits', 'Contact HR'],
    analyticsTags: ['hr', 'recruitment', 'hiring', 'talent'],
  },
  {
    id: 'saas',
    name: 'SaaS',
    description: 'Product demos, feature help, onboarding, trials',
    icon: '☁️',
    gradient: 'from-blue-500 to-cyan-500',
    color: '#3b82f6',
    categories: ['Software', 'Cloud', 'API Services', 'B2B', 'B2C'],
    systemPrompt: 'You are a SaaS product assistant. Help users with onboarding, feature questions, troubleshooting, account management, and upgrade paths. Guide users to relevant docs and drive product adoption.',
    suggestedMessages: ['How to get started?', 'Features & pricing', 'Integrations', 'Technical support'],
    welcomeMessage: 'Welcome! 🚀 Ready to explore our platform? I can help you get started and answer any questions!',
    quickActions: ['Start Free Trial', 'View Demo', 'Documentation', 'Contact Sales'],
    analyticsTags: ['saas', 'software', 'onboarding', 'product'],
  },
  {
    id: 'education',
    name: 'Education',
    description: 'Course info, enrollment, student support',
    icon: '📚',
    gradient: 'from-violet-500 to-indigo-500',
    color: '#8b5cf6',
    categories: ['Online Learning', 'Tutoring', 'K-12', 'Higher Ed', 'Training'],
    systemPrompt: 'You are an educational assistant. Help students and parents with course information, enrollment, scheduling, academic resources, and general inquiries. Be patient, encouraging, and supportive.',
    suggestedMessages: ['Browse courses', 'Enrollment info', 'Tuition & aid', 'Academic calendar'],
    welcomeMessage: 'Welcome to learning! 📚 How can I help you with your educational journey?',
    quickActions: ['Explore Courses', 'Enroll Now', 'Financial Aid', 'Student Resources'],
    analyticsTags: ['education', 'courses', 'students', 'learning'],
  },
  {
    id: 'support',
    name: 'Technical Support',
    description: 'Issue triage, troubleshooting, ticket management',
    icon: '🎧',
    gradient: 'from-rose-500 to-pink-500',
    color: '#f43f5e',
    categories: ['IT Support', 'Customer Service', 'Help Desk', 'SaaS Support'],
    systemPrompt: 'You are a technical support specialist. Help customers diagnose issues, provide step-by-step solutions, create support tickets, and escalate when needed. Be patient, clear, and solution-oriented.',
    suggestedMessages: ['Open a ticket', 'Common issues', 'Check status', 'Talk to a human'],
    welcomeMessage: 'Hi there! 👋 I\'m your support assistant. Describe your issue and I\'ll help you solve it!',
    quickActions: ['Open Ticket', 'Knowledge Base', 'Live Chat', 'Call Support'],
    analyticsTags: ['support', 'helpdesk', 'tickets', 'troubleshooting'],
  },
  {
    id: 'tourism',
    name: 'Travel & Tourism',
    description: 'Trip planning, bookings, recommendations',
    icon: '✈️',
    gradient: 'from-teal-500 to-cyan-500',
    color: '#14b8a6',
    categories: ['Travel Agency', 'Hotel', 'Tour Operator', 'Destination'],
    systemPrompt: 'You are a travel concierge. Help travelers plan trips, book hotels, find activities, get local recommendations, and manage reservations. Be enthusiastic and knowledgeable about destinations.',
    suggestedMessages: ['Plan a trip', 'Hotel deals', 'Popular destinations', 'Travel tips'],
    welcomeMessage: 'Ready for your next adventure? ✈️ Let me help you plan the perfect trip!',
    quickActions: ['Book a Trip', 'Special Offers', 'Destinations', 'Travel Guide'],
    analyticsTags: ['travel', 'tourism', 'hospitality', 'bookings'],
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    description: 'Property search, tours, mortgage info',
    icon: '🏠',
    gradient: 'from-amber-500 to-orange-500',
    color: '#f59e0b',
    categories: ['Residential', 'Commercial', 'Rental', 'Mortgage', 'Property'],
    systemPrompt: 'You are a real estate assistant. Help clients find properties, schedule viewings, answer neighborhood questions, explain financing options, and guide through the buying/selling process.',
    suggestedMessages: ['Find properties', 'Mortgage calculator', 'Schedule tour', 'Market trends'],
    welcomeMessage: 'Looking for your dream home? 🏡 Let\'s find the perfect property together!',
    quickActions: ['Search Properties', 'Mortgage Calculator', 'Schedule Tour', 'Sell Your Home'],
    analyticsTags: ['realestate', 'property', 'mortgage', 'housing'],
  },
  {
    id: 'logistics',
    name: 'Logistics',
    description: 'Shipment tracking, quotes, supply chain',
    icon: '🚚',
    gradient: 'from-yellow-500 to-amber-500',
    color: '#eab308',
    categories: ['Shipping', 'Warehousing', 'Supply Chain', 'Freight'],
    systemPrompt: 'You are a logistics assistant. Help customers track shipments, get quotes, understand services, manage deliveries, and resolve shipping issues. Be precise and efficient.',
    suggestedMessages: ['Track shipment', 'Get a quote', 'Shipping rates', 'Delivery times'],
    welcomeMessage: 'Welcome! 🚚 Need to track a shipment or get a shipping quote? I\'m here to help!',
    quickActions: ['Track Shipment', 'Get Quote', 'Shipping Guide', 'Contact Support'],
    analyticsTags: ['logistics', 'shipping', 'supplychain', 'freight'],
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    description: 'Crop info, supplier connection, market prices',
    icon: '🌾',
    gradient: 'from-green-600 to-emerald-500',
    color: '#16a34a',
    categories: ['Farming', 'Agri-Tech', 'Supplies', 'Produce'],
    systemPrompt: 'You are an agricultural assistant. Help farmers with crop information, connect with suppliers, provide market prices, offer farming tips, and answer agricultural queries. Be practical and knowledgeable.',
    suggestedMessages: ['Crop prices', 'Find suppliers', 'Farming tips', 'Weather impact'],
    welcomeMessage: 'Welcome, farmer! 🌾 How can I help you with your agricultural needs today?',
    quickActions: ['Market Prices', 'Find Suppliers', 'Farming Guide', 'Weather Report'],
    analyticsTags: ['agriculture', 'farming', 'agribusiness', 'supply'],
  },
];

export type BusinessPresetId = (typeof BUSINESS_PRESETS)[number]['id'];
