import { Plan } from '../types';

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'Perfect for getting started',
    price: 0,
    currency: 'USD',
    interval: 'month',
    features: [
      '1 chatbot',
      '500 conversations/month',
      '1,000 contacts',
      'Basic analytics',
      'Widget embedding',
    ],
    limits: {
      maxChatbots: 1,
      maxConversations: 500,
      maxContacts: 1000,
      maxTeamMembers: 1,
      maxKnowledgeSources: 3,
      aiMessagesPerMonth: 1000,
      aiTokensPerMonth: 50000,
      integrations: 0,
      customDomain: false,
      whitelabel: false,
      premiumSupport: false,
    },
  },
  {
    id: 'starter',
    name: 'Starter',
    description: 'For growing businesses',
    price: 29,
    currency: 'USD',
    interval: 'month',
    features: [
      '3 chatbots',
      '5,000 conversations/month',
      '5,000 contacts',
      'Advanced analytics',
      'Lead capture',
      'Email integrations',
    ],
    limits: {
      maxChatbots: 3,
      maxConversations: 5000,
      maxContacts: 5000,
      maxTeamMembers: 3,
      maxKnowledgeSources: 10,
      aiMessagesPerMonth: 5000,
      aiTokensPerMonth: 250000,
      integrations: 2,
      customDomain: false,
      whitelabel: false,
      premiumSupport: false,
    },
    isPopular: true,
  },
  {
    id: 'pro',
    name: 'Professional',
    description: 'For serious teams',
    price: 79,
    currency: 'USD',
    interval: 'month',
    features: [
      '10 chatbots',
      '25,000 conversations/month',
      '25,000 contacts',
      'Custom knowledge base',
      'CRM integrations',
      'Team collaboration',
      'Priority support',
    ],
    limits: {
      maxChatbots: 10,
      maxConversations: 25000,
      maxContacts: 25000,
      maxTeamMembers: 10,
      maxKnowledgeSources: 50,
      aiMessagesPerMonth: 25000,
      aiTokensPerMonth: 1000000,
      integrations: 10,
      customDomain: false,
      whitelabel: false,
      premiumSupport: true,
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'For large organizations',
    price: 299,
    currency: 'USD',
    interval: 'month',
    features: [
      'Unlimited chatbots',
      'Unlimited conversations',
      'Unlimited contacts',
      'White-label',
      'Custom domain',
      'SSO & SAML',
      'Dedicated support',
      'Custom integrations',
    ],
    limits: {
      maxChatbots: 999,
      maxConversations: 999999,
      maxContacts: 999999,
      maxTeamMembers: 999,
      maxKnowledgeSources: 999,
      aiMessagesPerMonth: 999999,
      aiTokensPerMonth: 99999999,
      integrations: 999,
      customDomain: true,
      whitelabel: true,
      premiumSupport: true,
    },
  },
];
